baseurl = "https://dazzling-kepler-2db754.netlify.com/"
title = "@woubuc"
author = "Wouter Buckens"
paginate = 10

pygmentsCodefences = true
pygmentsUseClasses = true

[taxonomies]
difficulty = "level"
tag = "tags"
